hepsi: derle calistir 
calistir: 
	./bin/Main
derle:
	g++ -I ./include/ -o ./lib/Kromozom.o -c ./src/Kromozom.cpp
	g++ -I ./include/ -o ./lib/Gen.o -c ./src/Gen.cpp
	g++ -I ./include/ -o ./bin/Main ./lib/Kromozom.o ./lib/Gen.o ./src/Main.cpp




